// calendarLinks.ts
// Generate deep‑links for calendar providers (Google, Outlook, Apple) from PTO plan

import { formatMonthDay } from '../models/dateUtils';
import { PTOPlan } from '../models/types';
import { generateICS } from '../ics/icsGenerator';

/**
 * Format a date string to Google Calendar's required format: YYYYMMDDTHHmmssZ
 * Uses UTC midnight for whole‑day events.
 */
function toGoogleCalendarDate(dateStr: string): string {
  // Input: YYYY‑MM‑DD
  const [year, month, day] = dateStr.split('-').map(Number);
  const d = new Date(Date.UTC(year, month - 1, day));
  return d.toISOString().replace(/[-:]/g, '').slice(0, 15) + 'Z';
}

/**
 * Generate a Google Calendar URL for a single break.
 */
export function generateGoogleCalendarLink(plan: PTOPlan): string {
  // Create one event per break (Google Calendar supports multi‑event via description)
  const firstBreak = plan.breaks[0];
  const title = `PTO Maxxing – ${plan.totalDaysOff} days off`;
  const start = toGoogleCalendarDate(firstBreak.oooStart);
  const end = toGoogleCalendarDate(firstBreak.oooEnd);
  
  const details = plan.breaks.map((brk: any, i: number) => {
    const holidays = brk.holidays.map((h: any) => h.name).join(' + ');
    return `${i + 1}. ${formatMonthDay(brk.oooStart)}‑${formatMonthDay(brk.oooEnd)}: ${holidays} (${brk.ptoUsed} PTO → ${brk.totalDaysOff} days off)`;
  }).join('\n');

  return `https://calendar.google.com/calendar/render?action=TEMPLATE` +
    `&text=${encodeURIComponent(title)}` +
    `&dates=${start}/${end}` +
    `&details=${encodeURIComponent(`Your PTO Maxxing plan:\n\n${details}\n\nTotal: ${plan.totalPtoUsed} PTO days → ${plan.totalDaysOff} days off (${plan.efficiency.toFixed(1)}× efficiency).\n\nGenerated at ptomaxxing.com`)}` +
    `&location=Work` +
    `&sprop=name:PTO Maxxing`;
}

/**
 * Generate an Outlook.com calendar link.
 */
export function generateOutlookLink(plan: PTOPlan): string {
  const firstBreak = plan.breaks[0];
  const start = toGoogleCalendarDate(firstBreak.oooStart);
  const end = toGoogleCalendarDate(firstBreak.oooEnd);
  const title = `PTO Maxxing – ${plan.totalDaysOff} days off`;
  
  const body = plan.breaks.map((brk: any, i: number) => {
    const holidays = brk.holidays.map((h: any) => h.name).join(' + ');
    return `${i + 1}. ${formatMonthDay(brk.oooStart)}‑${formatMonthDay(brk.oooEnd)}: ${holidays} (${brk.ptoUsed} PTO → ${brk.totalDaysOff} days off)`;
  }).join('\n') +
    `\n\nTotal: ${plan.totalPtoUsed} PTO days → ${plan.totalDaysOff} days off (${plan.efficiency.toFixed(1)}× efficiency).\n\nGenerated by PTO Maxxing`;

  return `https://outlook.live.com/calendar/0/deeplink/compose?` +
    `startdt=${start}` +
    `&enddt=${end}` +
    `&subject=${encodeURIComponent(title)}` +
    `&body=${encodeURIComponent(body)}` +
    `&path=/calendar/action/compose&rru=addevent`;
}

/**
 * Generate a data‑URL for Apple Calendar (iOS/macOS) that downloads .ics.
 */
export function generateAppleCalendarLink(plan: PTOPlan): string {
  const ics = generateICS(plan);
  const encoded = encodeURIComponent(ics);
  return `data:text/calendar;charset=utf-8,${encoded}`;
}

/**
 * Generate a downloadable ICS file (blob URL) for any platform.
 * Note: Not usable in React Native; for web only.
 */
export function generateICSBlob(plan: PTOPlan): string {
  const ics = generateICS(plan);
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  return URL.createObjectURL(blob);
}

/**
 * Main function returning all calendar‑related links for a plan.
 */
export function getCalendarLinks(plan: PTOPlan): {
  google: string;
  outlook: string;
  apple: string;
  ics: string;
  icsBlob: string;
} {
  return {
    google: generateGoogleCalendarLink(plan),
    outlook: generateOutlookLink(plan),
    apple: generateAppleCalendarLink(plan),
    ics: generateICS(plan),
    icsBlob: generateICSBlob(plan),
  };
}